name: redpesk-github-ci
run-name: ${{ github.actor }} has started a Github action
on: [pull_request, workflow_dispatch]

env:
  RP_FACTORY_PROJECT: 'github-ci-project'
  RP_FACTORY_APP: 'helloworld-binding'
  GH_SOURCE_BRANCH: ${{ github.head_ref }}
  GH_TARGET_BRANCH: ${{ github.base_ref }}
  GH_AUTHOR: ${{ github.actor }}
  GH_PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  build-application:
    runs-on: self-hosted
    steps:
      - name: Change branch in factory to source branch
        run: rp-cli applications update "$RP_FACTORY_APP" -p "$RP_FACTORY_PROJECT" --source-rev "$GH_SOURCE_BRANCH"

      - name: Run application build in redpesk factory
        run: rp-cli applications build "$RP_FACTORY_APP" -p "$RP_FACTORY_PROJECT" --comment "[Github CI] Started for PR '$GH_PR_NUMBER', from author '$GH_AUTHOR'" -v

      - name: Handle possible failure
        if: ${{ failure() }}
        run: rp-cli applications update "$RP_FACTORY_APP" -p "$RP_FACTORY_PROJECT" --source-rev "$GH_TARGET_BRANCH"
  
  test-application:
    runs-on: self-hosted
    needs: build-application
    steps:
      - name: Run application test in redpesk factory
        run: rp-cli applications test "$RP_FACTORY_APP" -p "$RP_FACTORY_PROJECT" --comment "[Github CI] Started for PR '$GH_PR_NUMBER', from author '$GH_AUTHOR'" -v

      - name: Change branch in redpesk factory
        if: ${{ always() }}
        run: rp-cli applications update "$RP_FACTORY_APP" -p "$RP_FACTORY_PROJECT" --source-rev "$GH_TARGET_BRANCH"
