name: redpesk-github-ci
run-name: ${{ github.actor }} has started a Github action
on: [pull_request, workflow_dispatch]

env:
  RP_REMOTE_FACTORY_URL: 'https://community-app.redpesk.bzh'
  RP_REMOTE_FACTORY_TOKEN: ${{ secrets.RP_REMOTE_FACTORY_TOKEN }}
  RP_FACTORY_PROJECT: ''
  RP_FACTORY_APP: ''

jobs:
  build-application:
    runs-on: ubuntu-latest
    steps:
      - name: Install redpesk-cli in the runner
        uses: ./.github/actions/install-rpcli
        with:
          factory-url: "$RP_REMOTE_FACTORY_URL"
          factory-token: "$RP_REMOTE_FACTORY_TOKEN"
      - name: Change branch in factory to source branch
        run: rp-cli applications update "$RP_FACTORY_APP" -p "$RP_FACTORY_PROJECT" --source-rev {{ github.head_ref }}
      - name: Run application build in redpesk factory
        run: rp-cli applications build "$RP_FACTORY_APP" -p "$RP_FACTORY_PROJECT" -v
